version: "2"
services:
  conductor-server:
    image: pdok/pdok-conductor-server:latest
    environment:
      - CONFIG_PROP=config.properties
    links:
      - elasticsearch
      - redis
    ports:
      - 8080:8080
  ui:
    image: pdok/pdok-conductor-ui:latest
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    links:
      - conductor-server
    ports:
      - 5000:5000
  redis:
    image: redis:4
  elasticsearch:
    image: elasticsearch:2.4
